version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - cnt_network
    container_name: nginx-proxy

  master-node:
    build:
      context: .
      dockerfile: master.Dockerfile
    expose:
      - "5999"
    environment:
      VIRTUAL_HOST: ~.*
      FLASK_RUN_PORT: 5999
      FLASK_ENV: development
    networks:
      - cnt_network
    container_name: cnt_master

  slave-node:
    build:
      context: .
      dockerfile: slave.Dockerfile
    expose:
      - "6000"
    environment:
      FLASK_RUN_PORT: 6000
      FLASK_ENV: development
    networks:
      - cnt_network

networks:
  cnt_network:
    external: true